# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4ff665f973d664e4feb2c49b8c3b1b6"
name = "my-wishlist"
handle = "my-wishlist-21"
application_url = "https://government-males-wax-highly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nard-store-for-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://government-males-wax-highly.trycloudflare.com/auth/callback",
  "https://government-males-wax-highly.trycloudflare.com/auth/shopify/callback",
  "https://government-males-wax-highly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
